[versions]
java = "21"
springBoot = "4.0.0"
springDependencyManagement = "1.1.7"
jib = "3.5.1"
archunit = "1.4.1"
jacoco = "0.8.12"
spotless = "8.1.0"
palantirJavaFormat = "2.38.0"
checkstyle = "10.13.0"
pmd = "7.0.0"
owaspDependencyCheck = "9.0.9"

[libraries]
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-flyway = { module = "org.springframework.boot:spring-boot-starter-flyway" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-docker-compose = { module = "org.springframework.boot:spring-boot-docker-compose" }

# Databases and Flyway
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql" }
postgresql = { module = "org.postgresql:postgresql" }

# Testing - Spring Boot managed versions
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
spring-boot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers" }
testcontainers-junit-jupiter = { module = "org.testcontainers:testcontainers-junit-jupiter" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql" }

# Other explicit versions
archunit = { module = "com.tngtech.archunit:archunit", version.ref = "archunit" }
checkstyle = { module = "com.puppycrawl.tools:checkstyle", version.ref = "checkstyle" }
pmd-java = { module = "net.sourceforge.pmd:pmd-java", version.ref = "pmd" }

[plugins]
springBoot = { id = "org.springframework.boot", version.ref = "springBoot" }
springDependencyManagement = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
jib = { id = "com.google.cloud.tools.jib", version.ref = "jib" }
jacoco = { id = "jacoco"}
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
owaspDependencyCheck = { id = "org.owasp.dependencycheck", version.ref = "owaspDependencyCheck" }
